[tool.poetry]
name = "pydantic2-resolve"
version = "1.1.1"
description = "create nested data structure easily"
authors = ["tangkikodo <allmonday@126.com>"]
readme = "README.md"
repository = "https://github.com/allmonday/pydantic2_resolve"
keywords = ["pydantic2", "fastapi"]
license = "MIT"
packages = [{include = "pydantic2_resolve"}]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^2.4"
aiodataloader = "^0.4.0"

[tool.poetry.group.dev.dependencies]
tox = "^4.4.6"
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
coverage = "^7.2.1"
aiosqlite = "^0.18.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.7"}
pytest-asyncio = "^0.21.0"
fastapi = "^0.100.0"
uvicorn = "^0.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
